### ISSUE TITLE
Interop metrics: HTTP fetching O(100k) test files is infeasible

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/results-analysis#29]
**Copied from https://github.com/web-platform-tests/results-collection/issues/454**

Runs produces ~22k individual test-file blobs - fetching all of these for 4 runs, individually is infeasibly slow, as (even if HTTP wasn't a bottleneck) the Cloud Storage API rate-limits requests.

While it is possible to create a client that batches these requests, it is a workaround at best.
It is apparent that the choice to shard the results hinges on the impact of an excessively large aggregated file on the wpt.fyi UI. However, having shards, and having aggregated files, is not mutually exclusive. We need to cover the use-case of processing all results (not just a per-file summary) across multiple browsers.

**Comment by lukebjerring** [comment]
This issue is mitigated by https://github.com/web-platform-tests/results-analysis/pull/21 and https://github.com/web-platform-tests/results-analysis/pull/20.

Will eventually be fixed with implementation of https://github.com/web-platform-tests/wpt.fyi/issues/55 which will persist full `wpt-report` output.
