### ISSUE TITLE
Execute another results-analysis run of ?label=stable

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/results-analysis#45]
Somewhat related to #44 

We'll eventually also want to run other configurations regularly for apples-to-apples interop, e.g. `experimental`, so if this manifests as a `matrix` in Travis that would make sense.

**Comment by Hexcles** [comment]
I'd like to recap our discussion we had off the thread:

Currently (without #46) the behaviour of the interop computer is the same as the default front page as they both use `?complete=true`: calculate/show the latest complete run with all four browsers; and if multiple versions of a browser are available, the latest version is chosen.

This is somewhat confusing as we aren't necessarily comparing apples to apples. My proposed solution is to keep the semantics of `complete` unchanged, and add `labels` support to results-analysis (and hence to the `/interop` view). The idea is to make `complete` and `labels` orthogonal so that it's possible to get "complete experimental runs" and "complete stable runs".

We can discuss what would be a reasonable default for 1) the front page (without any params) and 2) `?complete` with no labels specified.

**Comment by mdittmer** [comment]
Short term, here's my vote:

1. `complete=true` works as-is
2. `complete=true&labels=stable` means "complete" run sets must have all browsers with all labeled `stable`
3. `complete=true&labels=experimental` means "complete" run sets must have all browsers with all labeled `experimental`; there will be no such sets until we have experimental Safari and Edge

Long term: We probably want a more expressive query language so that clients can slice things as needed.
